version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: 
          name: Build
          command: |
            echo "Installing KubeBuilder"
            os=$(go env GOOS)
            arch=$(go env GOARCH)
            curl -sL https://go.kubebuilder.io/dl/2.2.0/${os}/${arch} | tar -xz -C /tmp/
            mv /tmp/kubebuilder_2.2.0_${os}_${arch} /$HOME/kubebuilder
            export PATH=$PATH:/$HOME/kubebuilder/bin
            kubebuilder version

            echo "Installing Kustomize"
            opsys=linux
            curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
              grep browser_download |\
              grep $opsys |\
              cut -d '"' -f 4 |\
              grep /kustomize/v |\
              sort | tail -n 1 |\
              xargs curl -O -L
            tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
            mv ./kustomize /$HOME/
            kustomize version

            make test

  docker:
    docker:
      - image: docker:stable-git
        environment:
          DOCKER_IMAGE: bjornmagnusson/mariadb-operator
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - run: 
          name: Build Docker image
          command: |
            make docker-build IMG=${DOCKER_IMAGE}:${CIRCLE_SHA1}
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              make docker-build IMG=${DOCKER_IMAGE}:${CIRCLE_TAG}
            fi
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              make docker-build IMG=${DOCKER_IMAGE}:canary
            fi
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker image push ${DOCKER_IMAGE_NAME}  