version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/bjornmagnusson/mariadb-operator
    steps:
      - checkout
      - run: 
          name: Bootstrap
          command: |
            echo "Installing Kustomize"
            opsys=linux
            curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
              grep browser_download |\
              grep $opsys |\
              cut -d '"' -f 4 |\
              grep /kustomize/v |\
              sort | tail -n 1 |\
              xargs curl -O -L
            tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
            mv ./kustomize $HOME
            export PATH=$PATH:$HOME
            kustomize version
      - run:
          name: Build
          command: |
            make

  docker:
    docker:
      - image: docker:stable-git
        environment:
          DOCKER_IMAGE: bjornmagnusson/mariadb-operator
    working_directory: /go/src/github.com/bjornmagnusson/mariadb-operator
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - checkout    
      - run: 
          name: Build Docker image
          command: |
            docker image build . -t ${DOCKER_IMAGE}:${CIRCLE_SHA1}
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker image build . -t ${DOCKER_IMAGE}:${CIRCLE_TAG}
            fi
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker image build . -t ${DOCKER_IMAGE}:canary
            fi
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker image push ${DOCKER_IMAGE}
      - run: 
          name: Bootstrap KinD cluster
          command: |
            apk add --no-cache curl make
            echo "---------------------"
            echo "Installing Kustomize"
            opsys=linux
            curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
              grep browser_download |\
              grep $opsys |\
              cut -d '"' -f 4 |\
              grep /kustomize/v |\
              sort | tail -n 1 |\
              xargs curl -O -L
            tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
            mv ./kustomize $HOME
            export PATH=$PATH:$HOME
            kustomize version
            echo "---------------------"
            echo "Installing Kind"
            curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-$(uname)-amd64
            chmod +x ./kind
            mv ./kind $HOME/kind
            export PATH=$PATH:$HOME
            kind version
            kind create cluster     
      - run:
          name: Deploy to cluster
          command: |
            make deploy IMG=${DOCKER_IMAGE}:${CIRCLE_SHA1}
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DOCKER_HUB
      - docker:  
          context: DOCKER_HUB
          requires:
            - build