
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - mariadb.bjornmagnusson.com
  resources:
  - databaseservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.bjornmagnusson.com
  resources:
  - databaseservers/status
  verbs:
  - get
  - patch
  - update
